# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        appname: cronmigration
        instanceId: cronmigration:${spring.application.instance_id:${random.value}}
        statusPageUrlPath: ${server.context-path}${management.context-path}/info
        healthCheckUrlPath: ${server.context-path}${management.context-path}/health
        leaseRenewalIntervalInSeconds: 2
        leaseExpirationDurationInSeconds: 5
        registryFetchIntervalSeconds: 1
        client:
          healthcheck:
            enabled: true
management:
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
spring:
    application:
        name: cronmigration
        jasper-report: /test/
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        show-sql: false
        hibernate:            
            ddl-auto: none
            dialect: org.hibernate.dialect.MySQL5Dialect
            naming:
                strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    batch:
        job:
            enabled: false

security:
    basic:
        enabled: false

server:
    session:
        cookie:
            http-only: true
jhipster: 
  async: 
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000
  cors: 
    allow-credentials: true
    allowed-headers: "*"
    allowed-methods: "GET, PUT, POST, DELETE, OPTIONS"
    allowed-origins: "*"
    exposed-headers: ~
    max-age: 1800
email:
  support:
    username: annamalai@techmango.net
    password: lk@mooka0208
application:
    cronjob:
      contractornegativetimesheet:  "* * 0/10 0 *  ?"
    live-date:  01/01/2017
    timeoff-request-hours:  8
    invoice-date:  01/01/2017
    invoice-no-of-partition:  150
logging:
  level:
    org.springframework.web: INFO
    com.tm: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: ${java.io.tmpdir}/batchjob-management.log