# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        appname: commonservicemanagement
        instanceId: common:${spring.application.instance_id:${random.value}}
        statusPageUrlPath: ${server.context-path}${management.context-path}/info
        healthCheckUrlPath: ${server.context-path}${management.context-path}/health
        leaseRenewalIntervalInSeconds: 2
        leaseExpirationDurationInSeconds: 5
        registryFetchIntervalSeconds: 1
        client:
          healthcheck:
            enabled: true
management:
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
spring:
    application:
        name: commonservicemanagement
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
        minimum-idle: 2
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false

security:
    basic:
        enabled: false

server:
    session:
        cookie:
            http-only: true
jhipster: 
  async: 
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000
  cors: 
    allow-credentials: true
    allowed-headers: "*"
    allowed-methods: "GET, PUT, POST, DELETE, OPTIONS"
    allowed-origins: "*"
    exposed-headers: ~
    max-age: 1800

application:
    live-date:  02/20/2016
    timeoff-request-hours:  8

            
keycloakappln:
    serverurl:  http://192.168.6.122:8080/auth
    realm:  timesheet
    admin-username:  timesheet_admin
    admin-password:  user@123
    clientid:  admin-cli

logging:
  file: ${java.io.tmpdir}/common-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: WARN
    org.hibernate: WARN
    com.tm.common: INFO 

mail:
  create-employee-url: http://192.168.6.35
  app-name: timetrackui
  app-module: expiry-create-password      